image: python:3.7-alpine

pages:
  stage: deploy
  script:
  - pip install -e --no-deps .
  - pip install -U sphinx sphinx_rtd_theme
  - sphinx-build -b html docs public
  artifacts:
    paths:
    - public
  only:
  - master
