image: python:3.7-alpine

pages:
  stage: deploy
  script:
  - pip install -U sphinx sphinx_rtd_theme sphinx-click
  - sphinx-apidoc -o docs/_source/ geohealthaccess --separate
  - sphinx-build -b html docs public
  artifacts:
    paths:
    - public
  only:
  - master
