version: '3'

services:
  app:
    build: .
    environment:
      EARTHDATA_USERNAME:
      EARTHDATA_PASSWORD:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      S3_REGION_NAME:
      # S3_ENDPOINT_URL:
      GOOGLE_APPLICATION_CREDENTIALS:
    volumes:
      - .:/code
