version: '3'

services:
  app:
    build:
      context: .
      args:
        DEV: "true"
    environment:
      EARTHDATA_USERNAME:
      EARTHDATA_PASSWORD:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      AWS_REGION:
      # S3_ENDPOINT_URL:
      GOOGLE_APPLICATION_CREDENTIALS:
    volumes:
      - .:/project
