name: geohealthaccess

channels:
  - default
  - conda-forge

dependencies:
  - python=3.8
  - pip=21
  - gdal=3.1
  - appdirs=1.4
  - beautifulsoup4=4.9
  - click=7
  - fiona=1.8
  - gcsfs=0.8
  - geopandas=0.9
  - loguru=0.5
  - numpy=1.20
  - pandas=1.2
  - rasterio=1.2
  - requests=2.25
  - s3fs=0.5
  - fsspec=0.9
  - shapely=1.7
  - tqdm=4.59
  - rasterstats=0.14
  - conda-build
  - pytest=6.2
  - pytest-cov
  - psutil
