name: geohealthaccess

channels:
  - default
  - conda-forge

dependencies:
  - python=3.9
  - pip=21
  - gdal=3.3
  - appdirs=1.4
  - beautifulsoup4=4.10
  - click=8.0
  - fiona=1.8
  - gcsfs=2021.10
  - geopandas=0.10
  - loguru=0.5
  - numpy=1.21
  - pandas=1.3
  - rasterio=1.2
  - requests=2.26
  - s3fs=2021.10
  - fsspec=2021.10
  - shapely=1.8
  - tqdm=4.62
  - rasterstats=0.16
  - conda-build
  - pytest=6.2
  - pytest-cov
  - psutil
