name: Publish Docker Image

on:
  release:
    types: [published]

jobs:
  push_to_registry:
   name: Push to Docker Hub
   runs-on: ubuntu-latest
   steps:
     - name: Checkout
       uses: actions/checkout@v2
     - name: Build and Push
       uses: docker/build-push-action@v1
       with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
         repository: blsq/geohealthaccess
         tag_with_ref: true
